# GoReleaser configuration for Cortex
# See: https://goreleaser.com

version: 2

before:
  hooks:
    # Install frontend dependencies and build
    - sh -c "cd web/frontend && npm ci && npm run build"
    # Copy frontend build to server
    - sh -c "rm -rf web/server/frontend/dist && cp -r web/frontend/dist web/server/frontend/"

builds:
  - id: cortex
    binary: cortex
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: cortex
    format: tar.gz
    name_template: 'cortex_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - example/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Refactors'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: '{{ .Env.GITHUB_REPOSITORY_OWNER }}'
    name: cortex
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Cortex {{ .Tag }} ({{ .Date }})

    Welcome to this new release of Cortex!

  footer: |
    ## Installation

    ### macOS (Intel)
    ```bash
    curl -L https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/cortex_{{ .Tag }}_darwin_amd64.tar.gz | tar xz
    sudo mv cortex /usr/local/bin/
    ```

    ### macOS (Apple Silicon)
    ```bash
    curl -L https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/cortex_{{ .Tag }}_darwin_arm64.tar.gz | tar xz
    sudo mv cortex /usr/local/bin/
    ```

    ### Linux (amd64)
    ```bash
    curl -L https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/cortex_{{ .Tag }}_linux_amd64.tar.gz | tar xz
    sudo mv cortex /usr/local/bin/
    ```

    ### Linux (arm64)
    ```bash
    curl -L https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/cortex_{{ .Tag }}_linux_arm64.tar.gz | tar xz
    sudo mv cortex /usr/local/bin/
    ```

    ### Windows
    Download the .zip file and extract `cortex.exe` to your PATH.

    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}
